version: 1
update_configs:
  - package_manager: javascript
    directory: package.json
    update_schedule: weekly
    automerged_updates:
      - match:
          dependency_type: all
          update_type: all
